/**
 * helper to hash and transform the seed to be more easily processed for image generation
 * @param {string} seed image generation seed 
 * @returns the seed, hashed and converted to base 8
 */
const seedToBase8String = async (seed) => {
    //get the SHA512 hash of the seed as a hex string
    let buffer = await crypto.subtle.digest("SHA-512", new TextEncoder("utf-8").encode(seed));
    let hash = "0x" + [...new Uint8Array(buffer)].map(x => x.toString(16).padStart(2, "0")).join("");
    //convert to bigInt and then to base 8
    return BigInt(hash).toString(8);
}

/**
 * Paint a canvas with an image generated by a seed with a given color pallette.
 * Assumes the canvas size is a scaled integer multiple of a width and height that multiply to 171.
 * 
 * @param {string} seed image generation seed
 * @param {*} pallette color pallette (array of 8 colors)
 * @param {HTMLCanvasElement} target canvas to paint to
 * @param {number} scalingFactor scaling factor for computed pixels to canvas pixels
 */
const generateAndPaintImage = async (seed, pallette, target, scalingFactor) => {
    //transform seed
    let b8string = await seedToBase8String(seed);
    //determine the pixel colors
    let pixelColors = b8string.split("").map(digit => pallette[parseInt(digit, 8)]);

    //get canvas context
    let ctx = target.getContext("2d");
    let pixelWidth = target.width / scalingFactor;
    let pixelHeight = target.height / scalingFactor;

    for (let px = 0; px < pixelWidth * pixelHeight; px++) {
        //set canvas fill style to color
        ctx.fillStyle = pixelColors[px];
        //draw a square with the color on the canvas
        const x = (px % pixelWidth) * scalingFactor;
        const y = (Math.floor(px / pixelWidth)) * scalingFactor;
        ctx.fillRect(x, y, scalingFactor, scalingFactor);
    };
}